services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP: api
        PORT: 3000
    image: 156321659479.dkr.ecr.ap-northeast-2.amazonaws.com/seoul-moment-api-dev:latest
    environment:
      - TZ=Asia/Seoul
    ports:
      - '3000:3000' # 로컬 테스트용 (ECS에선 미사용)
