version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${NODE_ENV}
        APP: api
        PORT: 3000
    environment:
      - TZ=Asia/Seoul # 컨테이너 내부 시간대를 KST로 설정
    image: api
    ports:
      - '3000:3000'
    networks:
      - app
    restart: always

networks:
  app:
    external: true
    name: app
